#!/bin/bash

print_usage() {
	echo "Usage:";
	echo "./bloodhound setup - setup additional dependencies";
    echo "./bloodhound serve - to test changes locally";
    echo "./bloodhound deploy - to deploy";
}

if [ "$#" -ne 1 ]; then
    print_usage
    exit -1
fi

if [ "$1" == "setup" ]; then
    npm install browserify -g
    exit -1
elif [ -z "`which browserify`" ]; then
	echo "Run with 'setup' option to install additional dependencies."
	exit -1
fi

case "$1" in
	"setup")
		npm install browserify -g
		exit 0
		;;
	"serve")
		watchify app.js -t babelify -o bundle.js &
		firebase serve
		exit 0
		;;
	"deploy"|"derploy")
		browserify app.js -t babelify -o bundle.js
		firebase deploy
		exit 0
		;;
	*)
		print_usage
		exit -1
		;;
esac

